- README.md
> Updated docs for postcards

- examples/create_check.php
- examples/create_job.php
- examples/create_pdf.php
- examples/create_sam.php
> fixed examples

- README.md
> fixes #19; fixes documentation link

- README.md
- examples/create_check.php
> feat(checks): added docs and example for check logo

- examples/create_check.php
- tests/Lob/Tests/Resource/BankAccountsTest.php
- tests/Lob/Tests/Resource/ChecksTest.php
Updates PHP wrapper to use latest, greatest check/bank stuff
> fix(update): fix check/bank addresses for new version

- src/Lob/Lob.php
- src/Lob/Resource.php
- tests/Lob/Tests/LobTest.php
Fixes a bug with specifying versions. Previous wrapper versions were allowing you to customize the `v1` part, but that's not what we wanted to do. 
Fixin' bugs is all in a day's work.
> fix(wrapper): Fix issue with specifying versions

- examples/create_check.php
- examples/create_job.php
- examples/create_letter.php
- examples/create_postcard.php
- examples/create_postcards_from_csv/create_postcards_from_csv.php
- examples/create_sam.php
- phpunit.xml.dist
- tests/Lob/Tests/LobTest.php
- tests/Lob/Tests/ResourceTest.php
in preparation for 2015-12-22.
> update postcard example to use size

- examples/create_check.php
- tests/Lob/Tests/Resource/BankAccountsTest.php
Updates check example and bank account test.
> Support API version 2016-03-21

- .travis.yml
- composer.json
- src/Lob/Resource.php
- tests/Lob/Tests/Resource/ChecksTest.php
- tests/Lob/Tests/ResourceTest.php
See #62, there were a number of small changes I had to made to support Guzzle 6.0 and the reason for the changes may not be obvious so feel free to question any changes and I'll do my best to explain why they were needed.
> Upgrading Guzzle to 6.0

- .travis.yml
- README.md
- src/Lob/Lob.php
- src/Lob/Resource.php
- src/Lob/Resource/Addresses.php
- src/Lob/Resource/IntlVerifications.php
- src/Lob/Resource/States.php
- src/Lob/Resource/USVerifications.php
- tests/Lob/Tests/Resource/AddressesTest.php
- tests/Lob/Tests/Resource/IntlVerificationsTest.php
- tests/Lob/Tests/Resource/USVerificationsTest.php
- tests/Lob/Tests/ResourceTest.php
> feat(verification): Add US/IntlVerifications ENG-2765

- README.md
For address verification launch.
> docs(readme): Add link to US Verification Details

- examples/README.md
- examples/create_postcard.php
- examples/create_postcards_from_csv/create_postcards_from_csv.php
What: update example to use merge_variables
Why: new HTML feature new version
> chore(examples): update to use merge_variables

- README.md
- src/Lob/Lob.php
- src/Lob/Resource/USZipLookups.php
- tests/Lob/Tests/Resource/USZipLookupsTest.php
**what**
- add US Zip Lookups API endpoint to wrapper
> feat(us-zip-lookups): add US Zip Lookups API endpoint to wrapper

- src/Lob/Resource.php
- tests/Lob/Tests/Resource/PostcardsTest.php
WHAT: adds capability to pass in idempotency headers
WHY: because I need to finish my intern project
> feat(idempotent-headers): adds capability to pass in idempotency headers

- tests/Lob/Tests/Resource/IntlVerificationsTest.php
> test(intl): Update international verifications tests

- src/Lob/Resource/USVerifications.php
- tests/Lob/Tests/Resource/USVerificationsTest.php
**What** 
- Allow us to send a `query` values when verifying US Addresses.
> feat(us-verifications): allow custom case query for US verifications

- README.md
- composer.json
- src/Lob/Lob.php
- src/Lob/Resource/USAutocompletions.php
- tests/Lob/Tests/Resource/USAutocompletionsTest.php
* Adds US Autocompletion resource + test
* Adds US Autocompletion info to the README
* Customers should be able to use our libraries to make autocompletion requests
> feat(us-autocompletions): add USAutocompletions

- README.md
- src/Lob/ResourceBase.php
> fix(errors): better error messages for 401s and 403s

- src/Lob/Exception/AuthorizationException.php
- src/Lob/Exception/ForbiddenException.php
- src/Lob/Exception/InternalErrorException.php
- src/Lob/Exception/LobException.php
- src/Lob/Exception/NetworkErrorException.php
- src/Lob/Exception/RateLimitException.php
- src/Lob/Exception/ResourceNotFoundException.php
- src/Lob/Exception/UnexpectedErrorException.php
- src/Lob/Exception/ValidationException.php
Fixes #100, making it easier to handle exceptions by providing a generic LobException class, from which all other custom exception classes inherit.
> feat(lob-exception): add generic LobException class for better exception handling

- src/Lob/ResourceBase.php
- tests/Lob/Tests/Resource/ChecksTest.php
- tests/Lob/Tests/Resource/LettersTest.php
- tests/Lob/Tests/Resource/PostcardsTest.php
Allows nested merge variables on resource creation
Advanced templating syntax
> chore(merge-variables): allow nested merge variables

- tests/Lob/Tests/Resource/USAutocompletionsTest.php
test was failing, the function was returning 1 and not throwing the exception, so i removed the test
> chore(failing-test) remove failing test

- .travis.yml
add more modern php versions for CI
> chore(add-php-versions) add more recent php versions to run tests

- composer.json
- src/Lob/Lob.php
OR'ing versions is || double pipe now
> chore(version-constraint) update to composer 2 standards 

- .github/workflows/run_tests_job.yml
- composer.json
- phpunit.xml.dist
- tests/Lob/Tests/LobTest.php
- tests/Lob/Tests/Resource/AddressesTest.php
- tests/Lob/Tests/Resource/BankAccountsTest.php
- tests/Lob/Tests/Resource/BulkIntlVerificationsTest.php
- tests/Lob/Tests/Resource/BulkUSVerificationsTest.php
- tests/Lob/Tests/Resource/CardOrdersTest.php
- tests/Lob/Tests/Resource/CardsTest.php
- tests/Lob/Tests/Resource/ChecksTest.php
- tests/Lob/Tests/Resource/IntlVerificationsTest.php
- tests/Lob/Tests/Resource/LettersTest.php
- tests/Lob/Tests/Resource/PostcardsTest.php
- tests/Lob/Tests/Resource/SelfMailersTest.php
- tests/Lob/Tests/Resource/USAutocompletionsTest.php
- tests/Lob/Tests/Resource/USReverseGeocodeLookupsTest.php
- tests/Lob/Tests/Resource/USVerificationsTest.php
- tests/Lob/Tests/Resource/USZipLookupsTest.php
- chore: move automated test running to Github Actions
- chore: update PHP versions
- chore: update tests for new version
- chore: update tests that cannot pass to correctly test functionality
What is not here:
- Code coverage with coveralls
> chore: move automated test running to Github Actions

- .gitignore
- composer.json
- composer.lock
Re: [DXP-930](https://lobsters.atlassian.net/browse/DXP-930)
- Remove ignore on composer lock file and provide a lock file
- Ran composer update
- Lock Guzzle to a previous version so all target versions of PHP are supported
> fix(composer) add lock file

- src/Lob/Lob.php
- src/Lob/Resource/Templates.php
https://docs.lob.com/#tag/Templates
Need templates support with this SDK
> add templates support

- tests/Lob/Tests/Resource/TemplatesTest.php
> chore(test) add template tests

- CODE_SNIPPETS.md
Add code snippets as captured from docs.lob.com
> chore(doc) add code snippets.md file

- MIGRATION.md
- Add migration guide from <= 3.x.x to 4.0.0
> chore: Add migration guide

- lib/Api/AddressesApi.php
- lib/Api/BankAccountsApi.php
- lib/Api/BillingGroupsApi.php
- lib/Api/CardOrdersApi.php
- lib/Api/CardsApi.php
- lib/Api/ChecksApi.php
- lib/Api/IntlAutocompletionsApi.php
- lib/Api/IntlVerificationsApi.php
- lib/Api/LettersApi.php
- lib/Api/PostcardsApi.php
- lib/Api/ReverseGeocodeLookupsApi.php
- lib/Api/SelfMailersApi.php
- lib/Api/TemplateVersionsApi.php
- lib/Api/TemplatesApi.php
- lib/Api/UsAutocompletionsApi.php
- lib/Api/UsVerificationsApi.php
- lib/Api/ZipLookupsApi.php
https://lobsters.atlassian.net/browse/DXP-1114
> Modified build fixes

- CODE_SNIPPETS.md
https://lobsters.atlassian.net/browse/DXP-1132
https://github.com/lob/sdks_openapi_gen/pull/245
> Add intlv code snip

- test/Integration/CardsApiSpecTest.php
- test/Integration/LettersApiSpecTest.php
https://lobsters.atlassian.net/browse/DXP-1172
> Temp remove extra service

- README.md
Added link to legacy PHP SDK in README.
[JIRA-1405](https://lobsters.atlassian.net/browse/DXP-1405)
> docs: legacy SDK link

- composer.json
Please provide a brief summary of changes made and files affected
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-XXX)
[Generator](https://github.com/lob/sdks_openapi_gen/pull/XX)
> updated version number

- composer.json
updating the version to release it on packagist
> updating version for the library

- composer.json
updating the composer version
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-XXX)
[Generator](https://github.com/lob/sdks_openapi_gen/pull/XX)
> AV4535 bupdating composer version
