- src/Lob/Resource.php
So that the user can catch and react to any 5XX and not purely just an HTTP 500.
> fix(errors): catch all 500s as internal server errors

- src/Lob/Resource/Routes.php
- tests/Lob/Tests/Resource/RoutesTest.php
For some reason we didn't have individual routes `/v1/routes/{id}` enabled in our wrapper. This PR enables it. It was already coded, we were just overwriting it.
> feat(routes): allow fetching of individual routes

- src/Lob/Lob.php
I just realized we haven't updated our client version in a while (a couple of releases). This value is used in each request when setting the User-Agent to let us know what version of the PHP wrapper customers are using. Once this is merged, I'll cut a new tag version (`v1.7.1`).
> chore(version): bump client version

- .travis.yml
-[x] Supports PHP 7.1, and removes support for 5.5, which has been deprecated since early 2016.
> feat(versions): Support PHP 7.1 and remove support for 5.5

- src/Lob/Exception/AuthorizationException.php
- src/Lob/Exception/ForbiddenException.php
- src/Lob/Exception/InternalErrorException.php
- src/Lob/Exception/NetworkErrorException.php
- src/Lob/Exception/RateLimitException.php
- src/Lob/Exception/ResourceNotFoundException.php
- src/Lob/Exception/UnexpectedErrorException.php
- src/Lob/Exception/ValidationException.php
- src/Lob/Lob.php
- src/Lob/Resource.php
- src/Lob/Resource/Addresses.php
- src/Lob/Resource/Areas.php
- src/Lob/Resource/BankAccounts.php
- src/Lob/Resource/Checks.php
- src/Lob/Resource/IntlVerifications.php
- src/Lob/Resource/Letters.php
- src/Lob/Resource/Postcards.php
- src/Lob/Resource/Routes.php
- src/Lob/Resource/USVerifications.php
- src/Lob/Resource/USZipLookups.php
- src/Lob/ResourceInterface.php
- tests/Lob/Tests/LobTest.php
- tests/Lob/Tests/Resource/AddressesTest.php
- tests/Lob/Tests/Resource/IntlVerificationsTest.php
- tests/Lob/Tests/Resource/LettersTest.php
- tests/Lob/Tests/Resource/PostcardsTest.php
- tests/Lob/Tests/Resource/RoutesTest.php
- tests/Lob/Tests/Resource/USVerificationsTest.php
- tests/Lob/Tests/Resource/USZipLookupsTest.php
> fix(resource): clean up resource and 100% coverage

- src/Lob/Resource.php
**What**
**Context**
As mentioned in #83, some people us the @ symbol in order to indicate "care of" section of an address. Currently the library interprets strings starting with `@` as files that need to be included in the request therefore a value of `@ DE ZIMMERMANN` will try to open the local file ` DE ZIMMERMANN` and err out.
Fixes #83
> fix(resource): better handling of import files

- src/Lob/Resource.php
Fixes #85. 
`getResponse()` can and does return `null` sometimes, so calling `getBody()` on it blindly can cause errors.
> Check for response before trying to use it.

- tests/Lob/Tests/LobTest.php
Removes the call to `/v1/us_verifications` in the test for ensuring that a specific API version is used.
> fix(build): Fix specific api version test

- src/Lob/Lob.php
- src/Lob/LobResource.php
- src/Lob/Resource/Addresses.php
- src/Lob/Resource/Areas.php
- src/Lob/Resource/BankAccounts.php
- src/Lob/Resource/Checks.php
- src/Lob/Resource/IntlVerifications.php
- src/Lob/Resource/Letters.php
- src/Lob/Resource/Postcards.php
- src/Lob/Resource/Routes.php
- src/Lob/Resource/USVerifications.php
- src/Lob/Resource/USZipLookups.php
- src/Lob/ResourceBase.php
**What & Why**
- It seems hhvm has `Resource` as a reserved class name. That being said, I'm not sure why this wasn't an issue until today.
> chore(resource): rename Resoruce to ResourceBase

- src/Lob/Resource/IntlVerifications.php
This is to fix the following error: `Declaration of Lob\Resource\IntlVerifications::create(array $data) must be compatible with Lob\ResourceBase::create(array $data, ?array $headers = NULL)`
> Change method signature to match ResourceBase

- src/Lob/Resource/Routes.php
- src/Lob/Resource/USZipLookups.php
- src/Lob/ResourceInterface.php
**What**
* Adds `$headers` arguments to all `create` methods that are overridden on resources.
* Makes the resource interface consistent with the resource base class.
**Note**
Merge this after #95
> fix(rescource-create): standardize resource create methods

- .travis.yml
- tests/Lob/Tests/Resource/IntlVerificationsTest.php
With the introduction of our International Verifications Test Mode, we need to update this test to ensure that we get a valid response.
> chore(intl-ver): update intl ver test

- .travis.yml
on php 7.3 XDEBUG_MODE=coverage needs to be added
see: https://github.com/sebastianbergmann/php-code-coverage/issues/834
> chore(fix-coverage) fix php 7.3 coverage generation

- README.md
- examples/README.md
- examples/create_check.php
- examples/create_letter.php
- examples/create_postcard.php
- examples/create_postcards_from_csv/create_postcards_from_csv.php
- examples/verify_addresses_from_csv/verify.php
- phpunit.xml.dist
- tests/Lob/Tests/LobTest.php
- tests/Lob/Tests/Resource/AddressesTest.php
- tests/Lob/Tests/Resource/BankAccountsTest.php
- tests/Lob/Tests/Resource/ChecksTest.php
- tests/Lob/Tests/Resource/IntlVerificationsTest.php
- tests/Lob/Tests/Resource/LettersTest.php
- tests/Lob/Tests/Resource/PostcardsTest.php
- tests/Lob/Tests/Resource/USAutocompletionsTest.php
- tests/Lob/Tests/Resource/USVerificationsTest.php
- tests/Lob/Tests/Resource/USZipLookupsTest.php
This PR removes the hardcoded API key and provides it via an environment variable in Travis (same as the other SDK clients). The previous API key has also been rotated and no longer works.
> chore: remove API keys from tests and examples

- src/Lob/Lob.php
**What**
Bumps client library version identifier from 3.0.6 to 3.1.0
**Why**
Cutting new release with added self mailer support
> chore: bump version 3.0.6 -> 3.1.0

- examples/README.md
- examples/cards/card.pdf
- examples/create_card.php
- examples/create_self_mailer.php
- src/Lob/Lob.php
- src/Lob/Resource/CardOrders.php
- src/Lob/Resource/Cards.php
- tests/Lob/Tests/Resource/CardOrdersTest.php
- tests/Lob/Tests/Resource/CardsTest.php
- tests/Lob/Tests/TestData/pdfs/card.pdf
**Why**
As we rollout Card-Affix for GA, we want to expose this functionality through our public SDK's. We will need to create and configure the necessary libraries for our card affix endpoints
**What**
- Create a resource for cards
- Create a resource for card orders, which require being passed a `card_id` since this mirrors the functionality of our card_orders endpoint (e.g. `GET/POST v1/cards/{card_id}/orders`
- Create tests for cards
- Create tests for card orders
- Create an example file using the combined functionality
> [feat]: Added SDK support for Cards and Card Orders endpoints

- .gitattributes
I've noticed that `.gitattributes` file is missing from it. It's actually a good idea to exclude unneeded dev files from the final production zip archive file, which is also downloaded by composer (unless --prefer -source is specified).
Those files are actually only useful when working on the library itself.
If you are not familiar, further information about export-ignore can be found below:
- http://www.pixelite.co.nz/article/using-git-attributes-exclude-files-your-release/
- https://madewithlove.be/gitattributes/
Hope it helps! 😊
> Exclude development files from distribution

- test/Integration/AddressesApiSpecTest.php
- test/Integration/BankAccountsApiSpecTest.php
- test/Integration/BillingGroupsApiSpecTest.php
- test/Integration/CardOrdersApiSpecTest.php
- test/Integration/CardsApiSpecTest.php
- test/Integration/ChecksApiSpecTest.php
- test/Integration/IntlAutocompletionsApiSpecTest.php
- test/Integration/IntlVerificationsApiSpecTest.php
- test/Integration/LettersApiSpecTest.php
- test/Integration/PostcardsApiSpecTest.php
- test/Integration/ReverseGeocodeLookupsApiSpecTest.php
- test/Integration/SelfMailersApiSpecTest.php
- test/Integration/TemplateVersionsApiSpecTest.php
- test/Integration/TemplatesApiSpecTest.php
- test/Integration/UsAutocompletionsApiSpecTest.php
- test/Integration/UsVerificationsApiSpecTest.php
- test/Integration/ZipLookupsApiSpecTest.php
[ticket](https://lobsters.atlassian.net/browse/DXP-1111)
Got rid of all the try catches because:
1. If the API does fail, don't we want it to break the tests rather than just print the errs?
2. The tests stop upon hitting an exception so nothing gets printed.
Done:
- problem with `include` param of List op
- The retrieve op test was skipped presumably b/c `next_url` and `previous_url` are `null`. I don't think these are meant to have values though. The example response for this op in docs.lob.com has those fields set to `null`. And I believe the `offset` field serves the same purpose as next and prev url.
> edit addresses+bankaccs integration tests

- README.md
Got rid of legacy docs link in README.
[JIRA-1228](https://lobsters.atlassian.net/browse/DXP-1228)
> remove legacy docs link of old SDK

- CODE_SNIPPETS.md
- config.php
- docs/Model/SingleLineAddress.md
- docs/Model/UsVerificationsWritable.md
- lib/Model/UsVerificationsWritable.php
- test/Integration/IdentityValidationApiSpecTest.php
- test/Integration/UsVerificationsApiSpecTest.php
- test/assets/lobster-family.csv
Changing Lob's address within the SDK to the current one: 2261 Market Street STE 5668
San Francisco, CA 94114. Limited changes to address 
[GC-1944](https://lobsters.atlassian.net/browse/GC-1944)
[Generator](https://github.com/lob/sdks_openapi_gen/pull/337)
[GC-1944]: https://lobsters.atlassian.net/browse/GC-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GC-1944/Change Lob Address
